{{- range $pluginName, $pluginConfigs := .Values.plugins }}
  {{- range $name, $config := $pluginConfigs }}
    {{- $fullName := printf "%s-%s" $pluginName $name }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "traefik-middleware.middlewareName" $fullName }}
  namespace: {{ include "traefik-middleware.namespace" $ }}
  labels:
    app.kubernetes.io/name: {{ include "traefik-middleware.middlewareName" $fullName }}
    helm.sh/chart: {{ include "traefik-middleware.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: traefik-middleware
    app.kubernetes.io/part-of: traefik
spec:
  plugin:
    {{ $pluginName }}:
      {{- toYaml $config | nindent 6 }}
  {{- end }}
{{- end }}
